# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: isntall script
      #   run: sudo apt-get update && sudo apt-get install script

      - name: test tty
        run: ps -p $$ -o tty= && tty

      - name: set PS1
        run: echo PS1='my_prompt' > ~/.bashrc

      - name: install expect
        run: |
          sudo apt update
          sudo apt install expect

      - name: expect
        run: expect ./expect-test

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install binutils

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: bash --version && objdump -tT $(which bash) | awk -v sym=environ ' $NF == sym { print $1; exit }'
